<a href="https://colab.research.google.com/github/brunokobi/Processamento_Imagens/blob/main/numpy_exercises_student.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Exercícios NumPy

In [ ]:
import numpy as np

**1.** Crie um array com 6 elementos em que os elementos possuem o padrão a seguir:

```
[0 2 4 6 8 10]
```

In [ ]:
array = np.arange(0, 12, 2)
print(array)

[ 0  2  4  6  8 10]


**2.** Crie um array $3 \times 4$ com o seguinte padrão:

```
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]
 ```

In [ ]:
array = np.arange(12).reshape(3, 4) ** 2
print(array)

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


**3.** Crie um array $7\times7$ no qual todos os elementos têm valor 0, exceto os da linha 3 e da coluna 3, que têm valor 1, como a seguir:

```
[[0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]
 [1 1 1 1 1 1 1]
 [0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]]
```

In [ ]:
array = np.zeros((7, 7), dtype=int)
array[3, :] = 1
array[:, 3] = 1
print(array)

[[0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]
 [1 1 1 1 1 1 1]
 [0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]]


**4.** Crie um array $5 \times 5$ com o seguinte padrão:

```
[[10  0  0  0  0]
 [ 0 10  0  0  0]
 [ 0  0 10  0  0]
 [ 0  0  0 10  0]
 [ 0  0  0  0 10]]
```

In [ ]:
array = np.eye(5, dtype=int) * 10
print(array)

[[10  0  0  0  0]
 [ 0 10  0  0  0]
 [ 0  0 10  0  0]
 [ 0  0  0 10  0]
 [ 0  0  0  0 10]]


**5.** Crie um array $5 \times 5$ com o seguinte padrão:

```
[[ 1  0  0  0  0]
 [ 0  4  0  0  0]
 [ 0  0  9  0  0]
 [ 0  0  0 16  0]
 [ 0  0  0  0 25]]
```

Utilize as funções `np.diag` e `np.arange`.

In [ ]:
array = np.diag(np.arange(1, 6) ** 2)
print(array)

[[ 1  0  0  0  0]
 [ 0  4  0  0  0]
 [ 0  0  9  0  0]
 [ 0  0  0 16  0]
 [ 0  0  0  0 25]]


**6.** Crie um array $3\times2\times4$ onde o elemento de índice $(i, j, k)$ tem valor $i^2$ para qualquer $j, k$, como abaixo:

```
[[[0 0 0 0]
  [0 0 0 0]]

 [[1 1 1 1]
  [1 1 1 1]]

 [[4 4 4 4]
  [4 4 4 4]]]
```

Dica: utilize a função `np.indices`.

In [ ]:
indices = np.indices((3, 2, 4))
array = indices[0] ** 2
print(array)

[[[0 0 0 0]
  [0 0 0 0]]

 [[1 1 1 1]
  [1 1 1 1]]

 [[4 4 4 4]
  [4 4 4 4]]]


**7.** Crie um array $5\times5$ onde o elemento de índice $(i,j)$ tem valor $i^2 + j^2$.

Dica: utilize a função `np.indices`.

In [7]:
x_indices, y_indices = np.indices((5, 5))
array = x_indices ** 2 + y_indices ** 2
print(array)

[[ 0  1  4  9 16]
 [ 1  2  5 10 17]
 [ 4  5  8 13 20]
 [ 9 10 13 18 25]
 [16 17 20 25 32]]


**8.** Gere uma matriz $10\times10$ de números aleatórios com distribuição normal de média 0 e desvio padrão 1. Calcule o *máximo* valor em cada linha e o *mínimo* valor em cada coluna.

Dica: utilize a função `np.randn`.

In [16]:
# Gerar a matriz 10x10 de números aleatórios com distribuição normal de média 0 e desvio padrão 1
matriz = np.random.randn(10, 10)

# Calcular o máximo de cada linha
maximos_linha = np.max(matriz, axis=1)
print("Máximo de cada linha:")
print(maximos_linha)

# Calcular o mínimo de cada coluna
minimos_coluna = np.min(matriz, axis=0)
print("\nMínimo de cada coluna:")
print(minimos_coluna)

Máximo de cada linha:
[1.00636071 1.19266596 2.09085682 2.61837063 0.48166156 1.53753754
 1.09466159 1.95802572 1.35272125 2.10906139]

Mínimo de cada coluna:
[-1.12774135 -0.56744992 -2.8685249  -1.42580302 -0.47732272 -1.19778021
 -1.13647654 -0.72130196 -1.0840308  -0.98684444]


**9.** Gere uma matriz $X \in \mathbb{R}^{5\times5}$ de números aleatórios com distribuição normal de média 1 e desvio padrão 3, isto é, $X \sim \text{N}(1, 3)$. Depois gere uma matriz $Y$ de mesmo formato cujo elemento $(i,j)$ terá valor $1$ se o elemento $(i,j)$ da matriz aleatória for menor que -5 ou maior do que 7, e zero caso contrário.
Conte o número de valores diferentes de zero nessa nova matriz.

Dica: se $X \sim \text{N}(0, 1)$, então $(\sigma \cdot X + \mu) \sim \text{N}(\mu, \sigma)$.

In [20]:
# Gerando uma matriz 5x5 de números aleatórios com distribuição normal de média 1 e desvio padrão 3
X = np.random.normal(loc=1, scale=3, size=(5, 5))

# Criando uma matriz Y com base na condição especificada
Y = np.where((X < -5) | (X > 7), 1, 0)

print(X)
print(Y)

[[ 3.45466548  0.75722281 -3.91206397  6.61635097  0.91644364]
 [-0.51587318 -2.38232403  0.83856016 -5.96770308 -1.25929318]
 [ 4.05803031  1.02414318  3.72286314  3.666961    1.71981919]
 [-3.61441395  4.55127069  1.00306512 -3.99573312  4.37950546]
 [-0.08095081  3.01635829  2.63020629 -0.99662289  5.52336171]]
[[0 0 0 0 0]
 [0 0 0 1 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


**10.** Use as regras de *broadcast* em seu benefício para gerar uma matriz $5\times5$ cujos elementos $(i,j)$ têm valor $i$. Faça o mesmo para gerar uma outra matriz de mesmo tamanho cujos elementos $(i,j)$ tenham valor $j$. Por fim, combine isso para gerar uma matriz também $5\times5$ cujos elementos $(i,j)$ tenham valor $2 i - j$.

Atenção: não utilizar `np.indices`.
Dica: utilizar soma com matriz de zeros com dimensões $10\times10$

In [23]:
# Gerar matriz com elementos i
i = np.arange(5)
matriz_i = np.zeros((5, 5)) + i.reshape((5, 1))

# Gerar matriz com elementos j
j = np.arange(5)
matriz_j = np.zeros((5, 5)) + j

# Gerar matriz com elementos 2i - j
matriz_final = 2 * matriz_i - matriz_j


print(matriz_i)
print(matriz_j)
print(matriz_final)

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[ 0. -1. -2. -3. -4.]
 [ 2.  1.  0. -1. -2.]
 [ 4.  3.  2.  1.  0.]
 [ 6.  5.  4.  3.  2.]
 [ 8.  7.  6.  5.  4.]]


**11.** Considere a matriz

$
X = \begin{bmatrix}
  9 & 3 & 8 \\
  7 & 4 & 5 \\
  2 & 3 & 1 \\
  2 & 10 & 9 \\
  8 & 9 & 2 \\
\end{bmatrix}.
$

Calcule $X_{shifted} = X - \mu$, onde $\mu$ é a média das linhas de $X$. Explore a funcionalidade de broadcasting e não utilize loops.


In [34]:
X = np.array([[9, 3, 8], [7, 4, 5], [2, 3, 1], [2, 10, 9], [8, 9, 2]])
X_shifted = np.zeros(X.shape)  # Mantenha esta linha

################## changer start
mu = np.mean(X, axis=1, keepdims=True)
X_shifted = X - mu
################## changer end

ans = np.array([[3.4, -2.8, 3.0], [1.4, -1.8, 0.0], [-3.6, -2.8, -4.0], [-3.6, 4.2, 4.0], [2.4, 3.2, -3.0]])
are_equal = np.allclose(X_shifted, ans, atol=1e-5)
if are_equal:
    print("Your function is correct.")
else:
    print("Your function is not correct.")

Your function is not correct.


**12.** A distância euclidiana entre dois vetores $u$ e $v$ de tamanho $n$ é dada por $\left\|u - v\right\|_2 = \sqrt{\sum_{i=1}^{n}(u_i - v_i)^2}.$

Dado os vetores (1-D arrays) a seguir, complete a função `euclidean_distance` para cálculo da distância. Não utilize loops, nem a função `np.linalg.norm`.

In [42]:
def euclidean_distance(u, v):
    distances = 0
    ##################
    # Calcula a diferença entre os vetores elemento por elemento
    diff = u - v
    # Eleva ao quadrado os elementos da diferença
    squared_diff = diff ** 2
    # Soma os quadrados dos elementos e tira a raiz quadrada
    distances = np.sqrt(np.sum(squared_diff))
    ##################
    return distances

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

distances = euclidean_distance(array1, array2)
are_equal = np.allclose(distances, np.linalg.norm(array1 - array2), atol=1e-5)
if are_equal:
    print("Your function is correct.")
else:
    print("Your function is not correct.")

Your function is correct.


**13.** Considere duas matrizes $X$ e $Y$, onde cada linha representa um vetor. Você foi solicitado a calcular a distância euclidiana entre as linhas de $X$ e as linhas correspondentes de $Y$. Escreva uma função que recebe as matrizes $X$ e $Y$ como entrada e retorna uma matriz $D$ onde cada elemento $(i,j)$ representa a distância euclidiana entre a linha $i$ de $X$ ($X_i$) e a linha $j$ de $Y$ ($Y_j$). O cálculo deve ser feito por meio de dois loops, conforme a equação

$D_{ij} = \left \|X_i - Y_j \right \|_2$

In [49]:
from scipy.spatial.distance import cdist


def calculate_distances_two_loops(X, Y):
    distances = np.zeros((X.shape[0], Y.shape[0]))
    ##################
    for i in range(X.shape[0]):
        for j in range(Y.shape[0]):
            # Calcula a diferença entre os vetores linha i de X e j de Y
            diff = X[i] - Y[j]
            # Eleva ao quadrado os elementos da diferença, soma e tira a raiz quadrada
            distances[i, j] = np.sqrt(np.sum(diff ** 2))
    ##################
    return distances


X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15]])
Y = np.array([[16, 17, 18], [19, 20, 21]])

distances = calculate_distances_two_loops(X, Y)
are_equal = np.allclose(distances, cdist(X, Y), atol=1e-5)
if are_equal:
    print("Your function is correct.")
else:
    print("Your function is not correct.")

Your function is correct.


**14.** O mesmo da questão anterior, mas agora utilizando um loop e broadcasting.

Dica: verifique se o resultado de `X[i] - Y` pode lhe ser útil na solução do exercício.

In [ ]:
# Create two 1D numpy array
X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15]])
Y = np.array([[16, 17, 18], [19, 20, 21]])

i = 2
print(X[i] - Y)

[[ -9  -9  -9]
 [-12 -12 -12]]


In [ ]:
def calculate_distances_one_loop(X, Y):
    distances = np.zeros((X.shape[0], Y.shape[0]))
    ##################
    # YOUR CODE HERE.#
    ##################
    return distances


distances = calculate_distances_one_loop(X, Y)
are_equal = np.allclose(distances, cdist(X, Y), atol=1e-5)
if are_equal:
    print("Your function is correct.")
else:
    print("Your function is not correct.")

Your function is not correct.


**15.** O mesmo da questão anterior, mas agora - você que é um mago do broadcasting - não pode utilizar loops.

Dica: verifique se o resultado de `X[:, np.newaxis, :] - Y` pode lhe ser útil na solução do exercício.

In [ ]:
# Create two 1D numpy array
X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15]])
Y = np.array([[16, 17, 18], [19, 20, 21]])

print(X[:, np.newaxis, :] - Y)

[[[-15 -15 -15]
  [-18 -18 -18]]

 [[-12 -12 -12]
  [-15 -15 -15]]

 [[ -9  -9  -9]
  [-12 -12 -12]]

 [[ -6  -6  -6]
  [ -9  -9  -9]]

 [[ -3  -3  -3]
  [ -6  -6  -6]]]


In [ ]:
def calculate_distances_vectorized(X, Y):
    distances = np.zeros((X.shape[0], Y.shape[0]))
    ##################
    # YOUR CODE HERE.#
    ##################
    return distances


distances = calculate_distances_one_loop(X, Y)
are_equal = np.allclose(distances, cdist(X, Y), atol=1e-5)
if are_equal:
    print("Your function is correct.")
else:
    print("Your function is not correct.")

Your function is not correct.
